### ISSUE TITLE
Can't add item using mobile view

### ISSUE THREAD

**Issue by tuxrinku** [nanawel/our-shopping-list#9] opened 2022-12-02 12:34 UTC
When using the app on mobile, I can't see the block to add a new item. Screenshot below. Everything else works fine. Any idea on how to fix this ?

![IMG_20221202_113529](https://user-images.githubusercontent.com/53600460/205293821-45f8f68f-67f1-44cf-b4b5-b7a992a0c936.jpg)

**Comment by nanawel** [comment] 2022-12-02 12:39
Sorry for that. What device are you using? What Android version?

**Comment by tuxrinku** [comment] 2022-12-02 12:42
My bad I completely forgot to put details. I'm using a Poco F2 pro, on Android 11. I tried both firefox and brave browser, the same thing happens on both.

**Comment by nanawel** [comment] 2022-12-02 12:50
I use both a Galaxy J5 (Android 5) and a Galaxy A51 (Android 12) with this app and I cannot reproduce this issue on either device. You might want to try yet another browser (Chrome?) just to be sure.

Sorry but atm I can't help :cry: 

I'll let this issue open in case someone else can add more details that could help identify the cause.

**Comment by tuxrinku** [comment] 2022-12-02 12:59
I think it's just "hiding" behind the android navigation bar, since I can see an element behind it. Probably because the navigation bar is on-screen and not physical. I'll try to play with some css and eventually figure a workaround.
Merci !

**Comment by nanawel** [comment] 2022-12-02 13:40
> Probably because the navigation bar is on-screen and not physical.

On my Galaxy A51 the navigation bar is also on-screen but I don't have this issue :confused:

**Comment by koeberlue** [comment] 2022-12-04 20:33
I'm having the same issue on a Fairphone 3 running Firefox 107.1.0 on LineageOS. My wife also has this issue on some Sony Xperia (will check the model and browser if it's important).

Some things I noticed:

### It works when using the built-in browser

As a workaround I am currently using [HomeApp](https://github.com/Domi04151309/HomeApp) to launch OurShoppingList. This opens the app in the built-in browser and everything works just fine.

### It works when I create a new list

Whenever I create an additional list, everything works fine. I can see the bottom bar to add new items. I can then browse to existing lists and see the bottom bar as well. I can even refresh the site and the bottom bar is still visible.

_But_ the very moment I close the tab and reopen it, the bottom bar is gone. I can only see the small grey bar as in the screenshot.

### Changing to desktop view does not help

In firefox you can change the viewport to desktop view. This will of course render everything way smaller and allows you to zoom in and move around. But whatever I try, there is still just a small grey bar at the bottom.

### Changing from desktop view back to mobile view works (kind of)

When I go into desktop view, zoom in a little bit, scroll down and _then_ change back to mobile view, the bottom bar suddenly appears. But now the top bar suddenly is gone.

Switching between desktop view and mobile view multiple times while zooming and scrolling around will then at some point fix everything.

**Comment by nanawel** [comment] 2022-12-05 06:16
I suspect this comes from these directives that always seemed like a wonky workaround to me:

https://github.com/nanawel/our-shopping-list/blob/6e6f3ba08548ac450a321b26d2ef069661f0f789/client/src/components/ListComponent.vue#L532-L536

Unfortunately my CSS skills are kinda poor so I would love to see what's the "proper way" to do that :thinking:

**Comment by onjour** [comment] 2023-01-12 15:55
I have the same issue too on my Android 13 running Mull 108.1.1 and Brave 1.46.154 (Chromium 108.0.5359.128)

Adding on @koeberlue remarks, my best way to resolve this was to use Our Shopping List as a [PWA](https://medium.com/progressivewebapps/how-to-install-a-pwa-to-your-device-68a8d37fadc1). This way both browsers work flawlessly. 

I believe that it is a big drawback for mobile users and that the docs might benefit from a note on that matter

**Comment by nanawel** [comment] 2023-01-15 14:52
Hi @tuxrinku @koeberlue @onjour 
I've made a tiny change on the CSS and deployed a temporary version at <https://dev.osl.lanterne-rouge.info>.

Since I'm unable to reproduce the issue myself with my own devices, could you tell me how it's working with yours?

**Comment by onjour** [comment] 2023-01-16 17:01
Hi @nanawel !

Thanks for the follow up! Well on my side it works very nicely. That did it for me on the two browsers I mentioned earlier 👍

**Comment by nanawel** [comment] 2023-01-17 12:42
The fix has been released: https://github.com/nanawel/our-shopping-list/releases/tag/2.5.1

**Comment by nanawel** [comment] 2023-01-17 16:00
Reopening. The new version broke the rendering on my device instead :sob:

**Comment by nanawel** [comment] 2023-01-22 15:28
Hi @onjour @tuxrinku @koeberlue

I'm trying a new approach, but I still need your help in confirming it works "not only on my computer" (or mobile): https://dev.osl.lanterne-rouge.info

Could you check again please? I need the results both in a **browser** and **as a PWA**, to be sure.

**Comment by onjour** [comment] 2023-01-23 13:20
Hi @nanawel! 

Thanks for digging into this. I tried yesterday and everything was fine, sorry to read that there are still issues on your side. I hope you'll figure that soon enough 👍

**Comment by nanawel** [comment] 2023-01-28 11:46
OK, found a lead: https://developer.chrome.com/blog/viewport-resize-behavior/

So this is new with recent versions of Chrome and derivatives. I could confirm this when I updated my browser (I scarcely do so).

**Comment by nanawel** [comment] 2023-01-28 13:28
This time I'm almost 100% confident that it now should be fixed the right way.

@tuxrinku @koeberlue @onjour can I ask you to test it again on <https://dev.osl.lanterne-rouge.info/> please?

- In a browser
- As a PWA
- with OSK (On Screen Keyboard) opened/closed (= searching/typing in the bottom bar)

Thanks

**Comment by nanawel** [comment] 2023-01-31 14:07
For the record, the root of this issue seems to be about
- viewport's height
- some changes that have been introduced in recent browsers regarding `vh` and `svh` CSS units (including Chrome 99+ and derivatives)
- probably also about what Vuetify has changed to comply to the previous changes but that make the UI buggy on older browsers (that don't understand `svh`)

So I've made a clean fix for recent browsers (it's the easiest), and also some workaround based on what I've read here and there on the web. So far I've managed to make it work on:
- my desktop PC (latest Firefox / latest Chromium)
- my Galaxy A51 (Android 11 / Firefox 109 / Chrome 109)
- my Galaxy J5 (Android 5 / Fennec 109 / Chromium 95)
  - **but** it's still buggy with Vivaldi 3.7 :frowning_face:

**Comment by koeberlue** [comment] 2023-01-31 15:17
> @tuxrinku @koeberlue @onjour can I ask you to test it again on https://dev.osl.lanterne-rouge.info/ please?

Just tested on my phone. Works great. Couldn't get it to make the search bar disappear :+1:

**Comment by nanawel** [comment] 2023-02-01 11:06
Closing now that [2.5.2](https://github.com/nanawel/our-shopping-list/releases/tag/2.5.2) is out.

Thanks @tuxrinku @koeberlue @onjour

**Closed by nanawel** 2023-02-01 11:06 UTC
Labels: help wanted, can't reproduce
